version: "3.7"

services:
  mongodb:
  image: mongo:latest
  ports:
    -27017:27017
  enviorment:
    - MONGO_INITDB_ROOT_USERNAME=admin_user
    - MONGO_INITDB_ROOT_PASSWORD=admin_pass
    - MONGO_INITDB_DATABASE=database
  volumes:
  - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro